// Multi-sheet XLSX export helper for finance/audit reports
import * as XLSX from "xlsx";

export interface SheetSpec {
  name: string;
  rows: Record<string, any>[];
  columns?: { key: string; label: string; width?: number }[];
}

export interface CoverMeta {
  reportTitle: string;
  statutoryBasis?: string;
  period?: string;
  fyLabel?: string;
  filters?: Record<string, string | number | boolean | undefined | null>;
  generatedBy?: string;
  notes?: string[];
  legalEntity?: string;
  gstin?: string;
}

/** Build a "Cover / Filing Reference" sheet with full audit-grade metadata. */
export function buildCoverSheet(meta: CoverMeta): SheetSpec {
  const now = new Date();
  const istFormatter = new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata", year: "numeric", month: "short", day: "2-digit",
    hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false,
  });
  const rows: Record<string, any>[] = [
    { field: "Report", value: meta.reportTitle },
    { field: "Legal Entity", value: meta.legalEntity || "P4U — Products For You" },
    { field: "GSTIN", value: meta.gstin || "—" },
    { field: "Statutory Basis", value: meta.statutoryBasis || "—" },
    { field: "Financial Year", value: meta.fyLabel || "—" },
    { field: "Period Covered", value: meta.period || "—" },
    { field: "Generated At (IST)", value: istFormatter.format(now) },
    { field: "Generated At (UTC)", value: now.toISOString() },
    { field: "Generated By", value: meta.generatedBy || "Admin Console" },
    { field: "Currency", value: "INR (₹)" },
    { field: "Rounding", value: "Per-row values rounded to 2 decimals; totals computed before rounding" },
  ];
  if (meta.filters) {
    Object.entries(meta.filters).forEach(([k, v]) => {
      if (v === undefined || v === null || v === "" || v === "all") return;
      rows.push({ field: `Filter — ${k}`, value: String(v) });
    });
  }
  if (meta.notes && meta.notes.length) {
    rows.push({ field: "", value: "" });
    rows.push({ field: "NOTES", value: "" });
    meta.notes.forEach((n, i) => rows.push({ field: `Note ${i + 1}`, value: n }));
  }
  rows.push({ field: "", value: "" });
  rows.push({ field: "Disclaimer", value: "Auto-generated from platform records. Cross-verify with GST portal & books of accounts before filing." });

  return {
    name: "Cover",
    rows,
    columns: [
      { key: "field", label: "Field", width: 32 },
      { key: "value", label: "Value", width: 80 },
    ],
  };
}

export function exportToXLSX(filename: string, sheets: SheetSpec[]) {
  const wb = XLSX.utils.book_new();
  for (const sheet of sheets) {
    let ws;
    if (sheet.columns && sheet.columns.length > 0) {
      const header = sheet.columns.map(c => c.label);
      const data = sheet.rows.map(r => sheet.columns!.map(c => r[c.key] ?? ""));
      ws = XLSX.utils.aoa_to_sheet([header, ...data]);
      ws["!cols"] = sheet.columns.map(c => ({ wch: c.width ?? Math.max(12, c.label.length + 2) }));
    } else {
      ws = XLSX.utils.json_to_sheet(sheet.rows);
    }
    const safeName = sheet.name.slice(0, 31);
    XLSX.utils.book_append_sheet(wb, ws, safeName);
  }
  const stamp = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${filename}-${stamp}.xlsx`);
}

// Indian financial year helper: FY runs Apr 1 → Mar 31
export function getFinancialYearRange(fyStartYear: number): { from: Date; to: Date; label: string } {
  return {
    from: new Date(fyStartYear, 3, 1, 0, 0, 0),
    to: new Date(fyStartYear + 1, 2, 31, 23, 59, 59),
    label: `FY ${fyStartYear}-${String(fyStartYear + 1).slice(-2)}`,
  };
}

export function getCurrentFinancialYear(): number {
  const now = new Date();
  return now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1;
}

/** Convert number to Indian numbering words (used on tax invoices & audit summaries). */
export function amountInWordsINR(amount: number): string {
  if (!isFinite(amount)) return "";
  const rupees = Math.floor(Math.abs(amount));
  const paise = Math.round((Math.abs(amount) - rupees) * 100);
  const sign = amount < 0 ? "Minus " : "";
  const words = numToIndianWords(rupees);
  const paiseWords = paise > 0 ? ` and ${numToIndianWords(paise)} Paise` : "";
  return `${sign}Rupees ${words}${paiseWords} Only`;
}

function numToIndianWords(n: number): string {
  if (n === 0) return "Zero";
  const ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
    "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];
  const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];
  const twoDigit = (x: number): string => x < 20 ? ones[x] : `${tens[Math.floor(x / 10)]}${x % 10 ? " " + ones[x % 10] : ""}`;
  const threeDigit = (x: number): string => {
    const h = Math.floor(x / 100); const r = x % 100;
    return `${h ? ones[h] + " Hundred" + (r ? " " : "") : ""}${r ? twoDigit(r) : ""}`;
  };
  let result = "";
  const crore = Math.floor(n / 10000000); n %= 10000000;
  const lakh = Math.floor(n / 100000); n %= 100000;
  const thousand = Math.floor(n / 1000); n %= 1000;
  const rest = n;
  if (crore) result += `${twoDigit(crore)} Crore `;
  if (lakh) result += `${twoDigit(lakh)} Lakh `;
  if (thousand) result += `${twoDigit(thousand)} Thousand `;
  if (rest) result += threeDigit(rest);
  return result.trim();
}

// India state codes (GST)
export const INDIA_STATES: { code: string; name: string }[] = [
  { code: "01", name: "Jammu and Kashmir" }, { code: "02", name: "Himachal Pradesh" },
  { code: "03", name: "Punjab" }, { code: "04", name: "Chandigarh" },
  { code: "05", name: "Uttarakhand" }, { code: "06", name: "Haryana" },
  { code: "07", name: "Delhi" }, { code: "08", name: "Rajasthan" },
  { code: "09", name: "Uttar Pradesh" }, { code: "10", name: "Bihar" },
  { code: "11", name: "Sikkim" }, { code: "12", name: "Arunachal Pradesh" },
  { code: "13", name: "Nagaland" }, { code: "14", name: "Manipur" },
  { code: "15", name: "Mizoram" }, { code: "16", name: "Tripura" },
  { code: "17", name: "Meghalaya" }, { code: "18", name: "Assam" },
  { code: "19", name: "West Bengal" }, { code: "20", name: "Jharkhand" },
  { code: "21", name: "Odisha" }, { code: "22", name: "Chhattisgarh" },
  { code: "23", name: "Madhya Pradesh" }, { code: "24", name: "Gujarat" },
  { code: "27", name: "Maharashtra" }, { code: "29", name: "Karnataka" },
  { code: "30", name: "Goa" }, { code: "32", name: "Kerala" },
  { code: "33", name: "Tamil Nadu" }, { code: "34", name: "Puducherry" },
  { code: "36", name: "Telangana" }, { code: "37", name: "Andhra Pradesh" },
];

export function stateName(code?: string | null): string {
  if (!code) return "—";
  return INDIA_STATES.find(s => s.code === code)?.name || code;
}
