ALTER TABLE public.customers DISABLE TRIGGER USER;
ALTER TABLE public.vendors DISABLE TRIGGER USER;
ALTER TABLE public.products DISABLE TRIGGER USER;
ALTER TABLE public.orders DISABLE TRIGGER USER;
ALTER TABLE public.categories DISABLE TRIGGER USER;
ALTER TABLE public.classified_ads DISABLE TRIGGER USER;
ALTER TABLE public.reviews DISABLE TRIGGER USER;
ALTER TABLE public.customer_addresses DISABLE TRIGGER USER;