ALTER TABLE public.customers ENABLE TRIGGER USER;
ALTER TABLE public.vendors ENABLE TRIGGER USER;
ALTER TABLE public.products ENABLE TRIGGER USER;
ALTER TABLE public.orders ENABLE TRIGGER USER;
ALTER TABLE public.categories ENABLE TRIGGER USER;
ALTER TABLE public.classified_ads ENABLE TRIGGER USER;
ALTER TABLE public.reviews ENABLE TRIGGER USER;
ALTER TABLE public.customer_addresses ENABLE TRIGGER USER;